# Default, Defaults
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Mariesa Dale
email: mariesa@mkdaledesign.com
description: Product Designer
baseurl: "https://mkdale.github.io/" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "https://mkdale.github.io/"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter: https://twitter.com/MariesaKDale
instagram: https://www.instagram.com/mariesakdale/
github: https://github.com/MKDale
dribbble: https://dribbble.com/MariesaKDale
medium: https://medium.com/@MariesaKDale

author: Mariesa Dale
authorBio: Seattle artist, DC designer
